name: unicode_helper
version: 0.1.0
author: Edwin Bühler <fulnir@gmail.com>
description: This library is a workaround for isLetter() isDigit() with unicode characters.
homepage: https://github.com/Fulnir/dart-unicode-helper
environment:
  sdk: '>=0.8.10+6 <2.0.0'
dev_dependencies:
  unittest: any
